package model;

import util.DB_Connector;
import java.sql.*;


public class PowerSource {
	
	private static Connection con = null;
	public String insertPowerSource(String pname, String paddress, String province, String type, String powergenerated, String maint_day,String head) {
		String output = "";
		
		try {
				con = DB_Connector.connect();
			
			if(con == null)
				return "Database connection failed for inserting data";
			
			// create a prepared statement
			String query = " insert into powersource (`ID`,`Name`,`Address`,`Province`,`Type`,`PowerGenerated`,`Maintenance_Day`,`Head_Engineer`)"
					 + " values (?, ?, ?, ?, ?, ?, ?, ?)";
			PreparedStatement preparedStmt = con.prepareStatement(query);
			// binding values
			preparedStmt.setInt(1, 0);
			preparedStmt.setString(2,pname);
			preparedStmt.setString(3,paddress);
			preparedStmt.setString(4,province);
			preparedStmt.setString(5,type);
			preparedStmt.setInt(6,Integer.parseInt(powergenerated));
			preparedStmt.setString(7,maint_day);
			preparedStmt.setString(8,head);
			
			// execute the statement
			preparedStmt.executeUpdate();
			con.close();
			output = "Data was successfully inserted";
		}
		
		catch (Exception e)
		{
			output = "Error while inserting the power source.";
			System.err.println(e.getMessage());
			e.printStackTrace();
		}
		
		return output;
	}
	
	public String readPowerSource()
	{
		String output = "";
		try
		{
			con = DB_Connector.connect();
			if (con == null)
				return "Database connection failed for reading data.";
			
			// Prepare the html table to be displayed
			output = "<table border='1'><tr><th>Power source name</th>" +
					"<th>Address of the power source</th><th>Province where it is located</th>" +
					"<th>Type of power source</th>"+
					"<th>Power generated by the power source in megawatts</th><th>Maintainence day</th>"
					+ "<th>Head Engineer</th></tr>";
			String query = "select * from powersource";
			Statement stmt = con.createStatement();
			ResultSet rs = stmt.executeQuery(query);
			
			// iterate through the rows in the result set
			while (rs.next())
			{
				String ID = Integer.toString(rs.getInt("ID"));
				String Name = rs.getString("Name");
				String Address = rs.getString("Address");
				String Province = rs.getString("Province");
				String Type = rs.getString("Type");
				String PowerGenerated = Integer.toString(rs.getInt("PowerGenerated"));
				String Maintenance_Day = rs.getString("Maintenance_Day");
				String Head_Engineer = rs.getString("Head_Engineer");
				
				// Add into the html table
				output += "<tr><td>" + Name + "</td>";
				output += "<td>" + Address + "</td>";
				output += "<td>" + Province + "</td>";
				output += "<td>" + Type + "</td>";
				output += "<td>" + PowerGenerated + "</td>";
				output += "<td>" + Maintenance_Day + "</td>";
				output += "<td>" + Head_Engineer + "</td>";
				
				// buttons
				output += "<td><input name='btnUpdate' type='button' value='Update'class='btn btn-secondary'></td>"
				+ "<td><form method='post' action=''>"
				+ "<input name='btnRemove' type='submit' value='Remove' class='btn btn-danger'>"
				+ "<input name='ID' type='hidden' value='" + ID
				+ "'>" + "</form></td></tr>";
			}
			con.close();
			// Complete the html table
			output += "</table>";
		}
		catch (Exception e)
		{
			output = "Error while reading the power source details.";
			System.err.println(e.getMessage());
		}
		return output;
	}
	
	public String updatePowerSource(String ID, String name, String address, String province, String type, String powerGen, String maint_day,String head)
	{
		String output = "";
		
		try
		{
			con = DB_Connector.connect();
			if (con == null)
				return "Database connection failed for updating data."; 
			
			// create a prepared statement
			String query = "UPDATE powersource SET Name=?,Address=?,Province=?,Type=?,PowerGenerated=?,Maintenance_Day=?,Head_Engineer=? WHERE ID=?";
			PreparedStatement preparedStmt = con.prepareStatement(query);
			
			// binding values
			preparedStmt.setString(1, name);
			preparedStmt.setString(2, address);
			preparedStmt.setString(3, province );
			preparedStmt.setString(4, type);
			preparedStmt.setInt(5, Integer.parseInt(powerGen));
			preparedStmt.setString(6, maint_day);
			preparedStmt.setString(7, head);
			preparedStmt.setInt(8, Integer.parseInt(ID));
			
			// execute the statement
			preparedStmt.execute();
			con.close();
			output = "The power source was updated successfully";
		}
		catch (Exception e)
		{
			output = "Error while updating the power source.";
			System.err.println(e.getMessage());
		}
		return output;
	}
	
	public String deletePowerSource(String ID)
	{
		String output = "";
		
		try
		{
			con = DB_Connector.connect();
			if (con == null)
				return "Database connection failed for deleting data."; 
			
			// create a prepared statement
			
		String query = "delete from powersource where ID=?";
		PreparedStatement preparedStmt = con.prepareStatement(query);
		
		// binding values
		preparedStmt.setInt(1, Integer.parseInt(ID));
		
		// execute the statement
		preparedStmt.execute();
		con.close();
		output = "Power source was deleted successfully";
	}
		catch (Exception e)
		{
			output = "Error while deleting the power source.";
			System.err.println(e.getMessage());
		}
		return output;
	}
}
